name: Build

on:
  push:
  pull_request:
  release:
    types: [ published ]

jobs:

  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

        coverage-driver:
          - "pcov"
          - "xdebug"
          - "xdebug3"

        exclude:
          - php-version: "8.0"
            coverage-driver: "xdebug"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "${{ matrix.coverage-driver }}"

      - name: "Install dependencies with composer"
        run: "composer update --no-ansi --no-interaction --no-progress"

      - name: "Run tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - run: composer require --dev php-coveralls/php-coveralls

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v