name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php: [ '5.6', '8.0' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer
        uses: php-actions/composer@dynamic-docker
        with:
          php-version: ${{ matrix.php }}
          command: install

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
