name: Tests

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        php: [ '5.6' ]

    runs-on: ubuntu-latest

      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install
      - name: PHPUnit testing
        uses: docker://php:5.5
        with:
          args: php vendor/bin/phpunit


    #    steps:
    #      - uses: actions/checkout@v2
    #
    #      - name: Install composer
    #        uses: php-actions/composer@dynamic-docker
    #        with:
    #          php_version: ${{ matrix.php }}
    #          command: install

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
