name: Tests

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        php: [ '5.6' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer
        uses: php-actions/composer@dynamic-docker
        with:
          php_version: ${{ matrix.php }}
          command: install
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run-script test
        
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

     # - name: Run tests
     #   run: vendor/bin/phpunit


    #    steps:
    #      - uses: actions/checkout@v2
    #
    #      - name: Install composer
    #        uses: php-actions/composer@dynamic-docker
    #        with:
    #          php_version: ${{ matrix.php }}
    #          command: install


